mqtt:
  enabled: true
  host: core-mosquitto
  port: 1883
  user: frigateu
  password: qqqqqqq7

face_recognition:
  enabled: true

  model_size: small
go2rtc:
  streams:
    dvor:
      - rtsp://10.0.0.7:554/user=admin_password=k1nno6g2_channel=0_stream=0&onvif=0.sdp?real_stream
    vorota:
      - rtsp://10.0.0.12:554/user=admin_password=tlJwpbo6_channel=0_stream=0&onvif=0.sdp?real_stream
    tambur:
      - rtsp://admin:bbbbbbb7@192.168.77.120/main

cameras:
  dvor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dvor
          input_args: preset-rtsp-restream
          roles: [detect, record]
    detect:
      enabled: true
    objects:
      track:
        - person
    record:
      enabled: true
      continuous:
        days: 7
      alerts:
        retain:
          days: 30
    snapshots:
      enabled: true
      retain:
        default: 30
    motion:
      threshold: 43
      contour_area: 45
      improve_contrast: true
  vorota:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/vorota
          input_args: preset-rtsp-restream
          roles: [detect, record]
    detect:
      enabled: true
    objects:
      track:
        - person
    record:
      enabled: true
      continuous:
        days: 7
      alerts:
        retain:
          days: 30
    snapshots:
      enabled: true
      retain:
        default: 30
    motion:
      threshold: 43
      contour_area: 45
      improve_contrast: true
  tambur:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/tambur
          input_args: preset-rtsp-restream
          roles: [detect, record]
    detect:
      enabled: true
    objects:
      track:
        - person
    record:
      enabled: true
      continuous:
        days: 7
      alerts:
        retain:
          days: 30
    snapshots:
      enabled: true
      retain:
        default: 30
    motion:
      threshold: 43
      contour_area: 45
      improve_contrast: true
  axis_2100:
    ffmpeg:
      inputs:
        - path: http://ahuserview:bbbbbbb7@10.0.0.49/axis-cgi/mjpg/video.cgi
          input_args: -f mjpeg
          roles: [detect]
      output_args:
        detect: -threads 2 -vf transpose=2 -f rawvideo -pix_fmt yuv420p
    detect:
      enabled: true
      width: 480
      height: 640
      fps: 2
    objects:
      track:
        - person
    record:
      enabled: false
    snapshots:
      enabled: true
      retain:
        default: 30

version: 0.17-0
semantic_search:
  enabled: false
  model_size: small
lpr:
  enabled: true
classification:
  bird:
    enabled: true
