mqtt:
  enabled: true
  host: core-mosquitto
  port: 1883
  user: frigateu
  password: qqqqqqq7

face_recognition:
  enabled: true

  model_size: small
go2rtc:
  streams:
    dvor:
      - rtsp://good:bbbbbbb7@10.0.0.7:554/channel=1&stream=0.sdp

cameras:
  dvor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dvor
          input_args: preset-rtsp-restream
          roles: [detect, record]
    detect:
      enabled: true
    objects:
      track:
        - person
    record:
      enabled: true
      continuous:
        days: 7
      alerts:
        retain:
          days: 30
    snapshots:
      enabled: true
      retain:
        default: 30
    motion:
      threshold: 43
      contour_area: 45
      improve_contrast: true

version: 0.17-0
semantic_search:
  enabled: false
  model_size: small
lpr:
  enabled: true
classification:
  bird:
    enabled: true
